### ISSUE TITLE
Feature request: Add locked sorting for mod panel in Solo menu

### ISSUE THREAD

**Issue by WookieOJ** [monkeymanboy/BeatSaberMarkupLanguage#138]
The mods tab in solo usually changes the order in between play sessions, it would be nice to be able to lock the order for this.

**Comment by nicoco007** [comment]
Hey! This has been fixed by 54c890e26943965e8263e4402e294189b511c059. Right now it just sorts in alphabetical order &ndash; I'll be investigating ways to customize this in the future. It'll be in the next release for Beat Saber 1.32.0. If I have time, I'll try to backport it to 1.29.1 as well along with some of the other improvements that have been made since it was last released for that version.
